---
title: "Untitled"
output: html_document
date: "2023-05-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Correlation

$$ y = \beta_0 + \beta_z x \\ H_0: \beta_1 = 0$$

```{r}
x <- rnorm(n = 1e5, mean = 3, sd = .5)
y <- rnorm(n = 1e5, mean = 150, sd = 10) + .2 * x

a = cor.test(y, x, method = "pearson") # Built-in
b = lm(y ~ 1 + x) # Equivalent linear model: y = Beta0*1 + Beta1*x
c = lm(scale(y) ~ 1 + scale(x))  # On scaled vars to recover r

a
b
c %>% summary() %>% tidy()

```


# One-Sample t-Test

$$ y = \beta_0 + \beta_1 * x \\ 
   x = 0 \\ 
   y = \beta_0 $$
   
   
``` {r}

# Built-in t-test
a = t.test(y)

# Equivalent linear model: intercept-only
b = lm(y ~ 1)

a
b
```


# Paired Sample t-Test

$$ y_2 - y_1 = \beta_0 \\ H_0: \beta_0 = 0 $$


# Independent t-Test

Independent t-test model: two means predict y

$$ y_i = \beta_0 + \beta_1 X_i \\ H_0: \beta_1 = 0 $$

``` {r}
# Built-in independent t-test on wide data
a = t.test(y, y2, var.equal = TRUE)

# Be explicit about the underlying linear model by hand-dummy-coding:
group_y2 = ifelse(group == 'y2', 1, 0)  # 1 if group == y2, 0 otherwise
b = lm(value ~ 1 + group_y2)  # Using our hand-made dummy regressor

# Note: We could also do the dummy-coding in the model
# specification itself. Same result.
c = lm(value ~ 1 + I(group == 'y2'))
```
