---
title: "DAGs Identity-Reintegration"
output: html_document
date: "2024-02-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





```{r, echo = FALSE}

dag_1 <- 
  
  dagify(
        'Purp' ~ 'MilID',
        'HS' ~ 'MilID',
        'Civs' ~ 'MilID',
        'Regr' ~ 'MilID',
        'Reg' ~ 'MilID',
         exposure = 'MilID', 
         outcome = 'Reg')


ggdag::tidy_dagitty(dag_1)

coordinates(dag_1) <- list(
  x = c(Civs = .75, Reg = .75, Purp = .75, HS = .75, Regr = .75, MilID = .5),
  y = c(
    HS = 1.03,
    Regr = 1.07,
    Purp = .97, 
    Civs = .93,
    Reg = 1, 
    MilID = 1
        )
)

(plot_dag_1 <-
ggdag(dag_1) +
  geom_dag_point(colour = 'white', fill = 'white') +
  geom_dag_edges() +
  geom_dag_text(color = 'black', size = 5) +
  theme_dag() +
  labs(title = 'Graphical Model: Chain of Events')
)

#ggsave(here::here('output/figures/graphical-models/dag_1'), plot = plot_chain)


adjustmentSets(dag_1)

(plot_dag_1_adj_set <-
ggdag_adjustment_set(dag_1) + theme_dag() +
  labs(title = 'Graphical Model 1: ')
)

#ggsave(here::here('output/figures/graphical-models/dag_chain_adj_set.jpeg'), plot = plot_chain_adj_set)
```




